name: Snyk IaC scan
on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - snyk_token: SNYK_TOKEN_WINTLTR
          - snyk_token: SNYK_TOKEN
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: snyk_scan
        uses: snyk/actions/iac@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets[matrix.snyk_token] }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high --target-name=keebackup_iac --report
          command: test
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Check on failures
        if: steps.snyk_scan.outcome != 'success'
        run: exit 1

      - name: Run random commands
        run: |
          echo "xd"
