name: Snyk IaC scan
on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: snyk_scan
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk_code_scan.sarif --severity-threshold=high --all-projects --target-name=keebackup_source_code --report
          command: test
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_code_scan.sarif

      - name: Check on failures
        if: steps.snyk_scan.outcome != 'success'
        run: exit 1

      - name: Run random commands
        run: |
          echo "xd"
